// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Xalapa Limpia.WindowsPhone")]
[assembly: AssemblyDescription("Xalapa Limpia Windows Phone Application")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("H. Ayuntamiento de Xalapa")]
[assembly: AssemblyProduct("Xalapa Limpia")]
[assembly: AssemblyCopyright("Copyright © 2016 H. Ayuntamiento de Xalapa")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.8.8")]
[assembly: AssemblyFileVersion("1.0.8.8")]
[assembly: ComVisible(false)]